apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-alert-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-alert-app
  template:
    metadata:
      labels:
        app: prod-alert-app
    spec:
    containers:
        - name: prod-alert-app
          image: docker.io/darklord995/prod-alert-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
